### ISSUE TITLE
Do you have a plan to release the labels of unlabeled data for further exploration?

### ISSUE THREAD

**Issue by zeyu-liu** [cvl-umass/semi-inat-2021#2]

**Comment by jongchyisu** [comment]
Yes, we will release the labels of the unlabeled data, as well as the taxonomy of out-of-class species. We will release those in July.

**Comment by jongchyisu** [comment]
Hello, I have released the labels for unlabeled data, as well as the taxonomy of all the categories (including in- and out-of-domain classes). You can find them in [this link](https://github.com/cvl-umass/ssl-evaluation/tree/main/data/semi_inat).
